#!/bin/bash

version="chpath - v1.0.0"
help=`cat <<-HELP
Usage: chpath <list|add|remove|edit> [paths ...]

Options:
    All options except list will require a reload of the terminal environment. This can be done by the alias 'reload' that the program writes to the bashrc file, or you can run \\\`source ~/.bashrc\\\` to reload the terminal

    list      Lists current paths in a readable format

    add       Adds path(s) to the current path structure (requires reload)

    remove    Removes path(s) from the current path structure (requires reload)

    edit      Edit path(s) in the current path structure (requires reload)

    reset     Resets the current path structure to the original path

    save      Saves the current path structure as the original
HELP
`

# chpath's Functions and Variables

# Vars
__cwd=`pwd`
__tmppre=`cat "$HOME/.path" | cut -d '+' -f1`
__tmppost=`cat "$HOME/.path" | cut -d '+' -f2`
prgroot="$HOME/.chpath"
changed=''
DEV=''

# Funcs
__args() {
  # Process args
  while [[ -n "$1" ]]; do
    # ALL CASE STATEMENT OPTIONS SHOULD END WITH 'return;;' in this function!!
    case "$1" in
      list )
        __list
        return;;
      add )
        shift
        [[ $DEV ]] && echo "Args passed to __add(): $@"
        if [[ ! -z "$1" ]]; then
          __add $@
        else
          echo "Required argument: PATH"
        fi
        return;;
      remove )
        shift
        [[ $DEV ]] && echo "Args passed to __remove(): $@"
        if [[ ! -z "$1" ]]; then
          __remove $@
        else
          echo "Required argument: PATH"
        fi
        return;;
      edit )
        shift
        [[ $DEV ]] && echo "Args passed to __edit(): $@"
        if [[ ! -z "$1" ]]; then
          __edit $@
        else
          echo "Required argument: PATH"
        fi
        return;;
      reset )
        __reset
        return;;
      save )
        __save
        return;;
      help )
        echo "$help"
        return;;
      version )
        echo "$version"
        return;;
      -V | --verbose )
        DEV=true
        [[ $DEV ]] && echo " - Verbose output - "
        ;;
      * ) # Catch-all
        echo "$help" | head -1
        echo "\"$1\" is not an argument!"
        return;;
    esac
  shift; done
}

# argcheck() { [[ "$1" ]] && return 1 || return; }
__list() { echo -e "${PATH//:/\\n}"; }
__add() {
  changed=true
  while [[ -n "$1" ]]; do
    case "$1" in
      -b | --before )
        shift;
        __tmppre="${1}:$__tmppre"
        ;;
      -a | --after )
        shift;
        __tmppost="${__tmppost}:${1}"
        ;;
      * )
        __tmppost="${__tmppost}:${1}"
        ;;
    esac
  shift; done
  [[ $DEV ]] && echo "Path file update: ${__tmppre}+${__tmppost}"
}
__remove() {
  while [[ -n "$1" ]]; do
    
  shift; done
}
__edit() {
  while [[ -n "$1" ]]; do
    local og=`echo "$1" | cut -d '=' -f1`
    local nu=`echo "$1" | cut -d '=' -f2`
    
    [[ $DEV ]] && echo "Editing $og to $nu"

    sed -i "s;$og;$nu;" "$HOME/.path" && changed=true || echo "Failed to edit $og to $nu!"

  shift; done
  [[ $DEV ]] && echo "Updated path file: `cat $HOME/.path`"
}
__reset() { cat $HOME/.pathog > "$HOME/.path" && echo "Path reset!"; }
__save() { cat $HOME/.path > "$HOME/.pathog" && echo "Path saved!"; }

# chpath's main code

repo=`find $HOME -type d -name chpath`

[[ `diff $repo/chpath $HOME/bin/chpath` ]] && $repo/install

__chpath() {
  # Run args
  [ -z "$1" ] && __args help || __args $@

  # Save users original path
  if [ ! -e "$HOME/.pathog" ]; then
    [[ $DEV ]] && echo "Creating .pathog"
    echo "+" > "$HOME/.pathog"
  fi

  # Set .path file if it doesn't exist
  if [ ! -e "$HOME/.path" ]; then
    [[ $DEV ]] && echo "Creating .path"
    echo "+" > "$HOME/.path"
  fi

  # Arg will set state of __chg to true to update the path file only when needed
  if [[ $changed ]]; then
    echo -e "${__tmppre}+${__tmppost}" > "$HOME/.path" && [[ $DEV ]] && echo "Path file written"
  fi

  # This will work with the program being force sourced
  source "$HOME/.bashrc"
}

__chpath $@

# Cleanup for accidental sourcing
unset __chpath __args __cwd repo __tmp DEV
unset version help
